import type { Alumni } from "@/components/directory/alumni-card"

export const alumniData: Alumni[] = [
  {
    id: "1",
    name: "Sarah Nakamya",
    avatar: "/professional-woman-portrait.png",
    title: "Senior Software Engineer",
    company: "Google",
    department: "Computer Science",
    graduationYear: "2019",
    location: "London",
    skills: ["Python", "Machine Learning", "Cloud"],
    linkedin: "https://linkedin.com",
    email: "sarah@example.com",
  },
  {
    id: "2",
    name: "James Ochieng",
    avatar: "/professional-african-man.png",
    title: "Product Manager",
    company: "Microsoft",
    department: "Information Technology",
    graduationYear: "2018",
    location: "Nairobi",
    skills: ["Product Strategy", "Agile", "UX"],
    linkedin: "https://linkedin.com",
    email: "james@example.com",
  },
  {
    id: "3",
    name: "Grace Mutesi",
    avatar: "/professional-woman-portrait-business.png",
    title: "Data Scientist",
    company: "Safaricom",
    department: "Data Science",
    graduationYear: "2021",
    location: "Kampala",
    skills: ["Data Analysis", "Python", "SQL"],
    linkedin: "https://linkedin.com",
    email: "grace@example.com",
  },
  {
    id: "4",
    name: "David Kimani",
    avatar: "/professional-man-portrait-suit.png",
    title: "CTO",
    company: "Flutterwave",
    department: "Software Engineering",
    graduationYear: "2015",
    location: "Lagos",
    skills: ["Leadership", "Fintech", "Architecture"],
    linkedin: "https://linkedin.com",
    email: "david@example.com",
  },
  {
    id: "5",
    name: "Amina Hassan",
    avatar: "/professional-woman-hijab-portrait.jpg",
    title: "Cybersecurity Analyst",
    company: "Deloitte",
    department: "Cybersecurity",
    graduationYear: "2020",
    location: "Dubai",
    skills: ["Security", "Penetration Testing", "Compliance"],
    linkedin: "https://linkedin.com",
    email: "amina@example.com",
  },
  {
    id: "6",
    name: "Peter Wanjiku",
    avatar: "/professional-man-casual-portrait.png",
    title: "DevOps Engineer",
    company: "Amazon",
    department: "Computer Science",
    graduationYear: "2022",
    location: "New York",
    skills: ["AWS", "Kubernetes", "CI/CD"],
    linkedin: "https://linkedin.com",
    email: "peter@example.com",
  },
  {
    id: "7",
    name: "Linda Auma",
    avatar: "/professional-woman-portrait-smile.jpg",
    title: "Full Stack Developer",
    company: "Andela",
    department: "Software Engineering",
    graduationYear: "2023",
    location: "Kampala",
    skills: ["React", "Node.js", "TypeScript"],
    linkedin: "https://linkedin.com",
    email: "linda@example.com",
  },
  {
    id: "8",
    name: "Michael Ssemakula",
    avatar: "/professional-man-portrait-glasses.png",
    title: "Network Architect",
    company: "MTN Uganda",
    department: "Network Engineering",
    graduationYear: "2017",
    location: "Kampala",
    skills: ["Networking", "Cisco", "5G"],
    linkedin: "https://linkedin.com",
    email: "michael@example.com",
  },
  {
    id: "9",
    name: "Faith Njeri",
    avatar: "/professional-woman-corporate-portrait.png",
    title: "AI Research Scientist",
    company: "OpenAI",
    department: "Data Science",
    graduationYear: "2019",
    location: "Remote",
    skills: ["Deep Learning", "NLP", "Research"],
    linkedin: "https://linkedin.com",
    email: "faith@example.com",
  },
  {
    id: "10",
    name: "Emmanuel Mugisha",
    avatar: "/young-professional-portrait.png",
    title: "Blockchain Developer",
    company: "Binance",
    department: "Computer Science",
    graduationYear: "2021",
    location: "Kigali",
    skills: ["Solidity", "Web3", "DeFi"],
    linkedin: "https://linkedin.com",
    email: "emmanuel@example.com",
  },
  {
    id: "11",
    name: "Joy Akinyi",
    avatar: "/professional-woman-portrait-tech.jpg",
    title: "UX Designer",
    company: "Spotify",
    department: "Information Technology",
    graduationYear: "2020",
    location: "London",
    skills: ["Figma", "User Research", "Prototyping"],
    linkedin: "https://linkedin.com",
    email: "joy@example.com",
  },
  {
    id: "12",
    name: "Robert Oduya",
    avatar: "/professional-executive-portrait.png",
    title: "Engineering Manager",
    company: "Meta",
    department: "Software Engineering",
    graduationYear: "2016",
    location: "New York",
    skills: ["Team Leadership", "System Design", "Mentoring"],
    linkedin: "https://linkedin.com",
    email: "robert@example.com",
  },
]
