export interface ExecutiveMember {
  id: string
  name: string
  position: string
  photo: string
  email?: string
  phone?: string
  bio?: string
  linkedIn?: string
}

export const executiveCommittee: ExecutiveMember[] = [
  {
    id: "1",
    name: "Mr. Okwi Simon",
    position: "Chairperson",
    photo: "/professional-african-woman-executive-chairperson.jpg",
    email: "chairperson@uictalumni.org",
    phone: "+256 706 923 655",
    bio: "Leading the alumni association with over 15 years of experience in ICT leadership.",
    linkedIn: "https://linkedin.com/in/sarahnakamya",
  },
  {
    id: "2",
    name: "Ms. Namanya Julian",
    position: "Vice Chairperson",
    photo: "/professional-african-man-vice-chairperson-suit.jpg",
    email: "vicechairperson@uictalumni.org",
    phone: "+256 701 234 567",
    bio: "Dedicated to fostering alumni connections and career development initiatives.",
    linkedIn: "https://linkedin.com/in/johnmukasa",
  },
  {
    id: "3",
    name: "Mr. Engole Allan Gideon",
    position: "General Secretary",
    photo: "/professional-african-woman-secretary-corporate.jpg",
    email: "secretary@uictalumni.org",
    phone: "+256 788 485 229",
    bio: "Ensuring smooth operations and effective communication across all alumni chapters.",
    linkedIn: "https://linkedin.com/in/graceachieng",
  },
  {
    id: "4",
    name: "Ms. Shamim kbabiito",
    position: "Treasurer",
    photo: "/professional-african-man-treasurer-finance.jpg",
    email: "treasurer@uictalumni.org",
    phone: "+256 704 997 263",
    bio: "Managing financial resources with transparency and accountability.",
    linkedIn: "https://linkedin.com/in/davidopio",
  },
  {
    id: "5",
    name: "Mr. Humphreys Muteese",
    position: "Publicity Secretary",
    photo: "/professional-african-woman-marketing-publicity.jpg",
    email: "publicity@uictalumni.org",
    phone: "+256 776 513 239",
    bio: "Promoting alumni activities and enhancing the association's public image.",
    linkedIn: "https://linkedin.com/in/faithnamukasa",
  },
  {
    id: "6",
    name: "Ms. Joan Apolot",
    position: "ICT & Engineering Representative",
    photo: "/professional-african-man-engineer-technology.jpg",
    email: "engineering@uictalumni.org",
    phone: "+256 775 290 895",
    bio: "Bridging technology innovations with alumni career opportunities.",
    linkedIn: "https://linkedin.com/in/peterssemakula",
  },
  {
    id: "7",
    name: "Mr. Muyonjo F.A Mugwiri",
    position: "Ex-Officio",
    photo: "/professional-african-woman-professor-academic.jpg",
    email: "exofficio@uictalumni.org",
    phone: "+256 776 385 853",
    bio: "Providing strategic guidance and institutional memory to the association.",
    linkedIn: "https://linkedin.com/in/agneskirabo",
  },
  {
    id: "8",
    name: "Mr. Aventino Ahimbisibwe",
    position: "Guild Representative",
    photo: "/professional-young-african-man-student-leader.jpg",
    email: "guild@uictalumni.org",
    phone: "+256 784 821 300",
    bio: "Connecting current students with alumni for mentorship and networking.",
    linkedIn: "https://linkedin.com/in/briankato",
  },
  {
    id: "9",
    name: "Ms. Grace Komujuni Namirembe",
    position: "Management Representative",
    photo: "/professional-african-woman-management-executive.jpg",
    email: "management@uictalumni.org",
    phone: "+256 703 842 949",
    bio: "Representing university management interests and facilitating institutional partnerships.",
    linkedIn: "https://linkedin.com/in/margaretnabukenya",
  },
  {
    id: "10",
    name: "Mr. Patrick Kakeeto",
    position: "Governing Council Representative",
    photo: "/professional-african-man-council-governance.jpg",
    email: "council@uictalumni.org",
    phone: "+256 783 988 654",
    bio: "Ensuring alumni voices are heard at the highest governance levels.",
    linkedIn: "https://linkedin.com/in/samuelwasswa",
  },
  {
    id: "11",
    name: "Eng. Edgar Ayine. M",
    position: "Social & Welfare Secretary",
    photo: "/professional-african-woman-social-welfare.jpg",
    email: "welfare@uictalumni.org",
    phone: "+256 774 313 958",
    bio: "Coordinating social events and welfare programs for alumni members.",
    linkedIn: "https://linkedin.com/in/esthernansubuga",
  },
  {
    id: "12",
    name: "Mr. Erizura Tugume",
    position: "Social Media & Technical Support",
    photo: "/professional-african-man-social-media-technology.jpg",
    email: "socialmedia@uictalumni.org",
    phone: "+256 788 774 999",
    bio: "Managing digital presence and providing technical support for alumni platforms.",
    linkedIn: "https://linkedin.com/in/isaacmugisha",
  },
  {
    id: "13",
    name: "Ms. Ritah Amongin",
    position: "Patron",
    photo: "/professional-african-woman-communications-media.jpg",
    email: "viceinfo@uictalumni.org",
    phone: "+256 712 345 678",
    bio: "Supporting publicity efforts and managing information dissemination.",
    linkedIn: "https://linkedin.com/in/ritahamongin",
  },
]
